title: Joanna Lee
logo: /assets/img/logo.png
profile-pic: /assets/img/profile-pic.png
description: AI Innovation for People Responsibly
show_downloads: false
google_analytics:
# theme: jekyll-theme-waves
linkedin_my_url: https://www.linkedin.com/in/joannaleecy
blog_my_url: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7181416432075726849
github_my_url: https://github.com/joannaleecy
kaggle_my_url: https://www.kaggle.com/joannaleecy